config/routes.rb
Myapp::Application.routes.draw do
  
  

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get '/dashboard', to: 'dashboard#index'

  resources :tickets

  resources :users do
    resources :tickets
  end

  get "home/index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    if current_user.has_role? :client
      @tickets = current_user.tickets
    elsif current_user.has_role? :admin or current_user.has_role? :moderator
      @tickets = Ticket.all
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
  <h1><%= current_user.roles.first.capitalize %> Dashboard</h1>
<% end %>

<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.body %></td>
        <td><%= ticket.user.full_name %></td>
        <td><%= link_to 'Show', user_ticket_path(ticket.user, ticket) %></td>
        <td><%= link_to 'Edit', edit_user_ticket_path(ticket.user, ticket) %></td>
        <td><%= link_to 'Destroy', user_ticket_path(ticket.user, ticket), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_user_ticket_path(current_user) %>